### ISSUE TITLE
Undefined property $userManager

### ISSUE THREAD

**Issue by sonnycabali** [rzproject/cms-sandbox#3]
This is the error I'm getting when updating record using EntityAudit

<strong>Notice: Undefined property: XXX\XXX\Admin\XXXAdmin::$userManager in C:\server\var\vhost\acesmarine\vendor\rmzamora\user-bundle\Sonata\UserBundle\Admin\Model\UserAdmin.php line 187</strong>

I tried tracing it and it happens in the PreUpdate callbacks where the usermanager is not set

**Comment by rmzamora** [comment]
How do I reproduce the error?
